var title =
[
   {
      'category':'Đề số 1',
      'question':
      [
       {
         'ques':'Một khu chợ đậm chất SG cổ kính, một biểu tượng của thành phố từ thời Pháp thuộc',
         'a':'Chợ Bà Chiểu',
         'b':'Chợ Bình Tây',
         'c':'Chợ Bến Thành',
         'd':'Chợ An Đông',
         'true':'c',
        },
        {
         'ques':'Một cây cầu đi bộ thu hút giới trẻ Sài Gòn ở quận 7 với hệ thống đèn LED và hệ thống phun nước lung linh.',
         'a':'Cầu Xanh',
         'b':'Cầu Thủ Thiêm',
         'c':'Cầu Phú Mỹ',
         'd':'Cầu Ánh Sao',
         'true':'d',
        },
        {
         'ques':'Một loại chè đã làm mưa làm gió giới trẻ Việt Nam nói chung và Sài Gòn nói riêng trong 1 thời gian dài đó là chè',
         'a':'Khúc côn cầu',
         'b':'Khúc cây',
         'c':'Khúc mắc',
         'd':'Khúc bạch',
         'true':'d',
        },
        {
         'ques':'Tuyến đường nhộn nhịp của Sài Gòn, được tái cải tạo từ trục đường có sẵn ở cổng Nam thành phố theo hướng Đông – Tây',
         'a':'Đường Điện Biên Phủ',
         'b':'Đại lộ Võ Văn Kiệt',
         'c':'Đường Tôn Đức Thắng',
         'd':'Đường Nguyễn Tất Thành',
         'true':'b',
        },
        {
         'ques':'Câu hát “Sài Gòn đẹp quá Sài Gòn ơi….” nằm trong bài hát nào về Sài Gòn thân thương?',
         'a':'Đẹp lắm Sài Gòn',
         'b':'Sài Gòn Đẹp Lắm',
         'c':'Sài Gòn trong tôi',
         'd':'Tôi trong Sài Gòn',
         'true':'b',
        },
     ],
   },
   {
     'category':'Đề số 2',
     'question':
     [
        {
         'ques':'Tên gọi thân thương người Sài Gòn dành cho những con đường Trần Huy Liệu, Trần Nhân Tông, Nguyễn Thị Minh Khai.',
         'a':'Phố đi bộ',
         'b':'Phố Tây',
         'c':'Phố sách cũ',
         'd':'Phố ăn vặt',
         'true':'c',
        },
        {
         'ques':'Một địa điểm gắn liền với sự kiện giải phóng miền Nam, nằm trên đường Nam Kỳ Khởi Nghĩa.',
         'a':'Café bệt',
         'b':'Dinh Độc Lập',
         'c':'Trường THPT Marie Curie',
         'd':'Chùa Vĩnh Nghiêm',
         'true':'b',
        },
        {
         'ques':'Một nhà thờ Công Giáo lâu đời, gần Dinh Độc Lập, thu hút rất nhiều bạn trẻ tham quan và chụp ảnh.',
         'a':'Nhà thờ Đức Bà',
         'b':'Nhà thờ Tân Định',
         'c':'Nhà thờ Dòng Chúa Cứu Thế',
         'd':'Nhà thờ Huyện Sĩ',
         'true':'a',
        },
        {
         'ques':'Ẩm thực đặc trưng chưa xa đã nhớ của Sài Gòn là món nào sau đây?',
         'a':'Bún đậu mắm tôm, bún chả, trà chanh',
         'b':'Cơm tấm, phở, cà phê sữa đá',
         'c':'Bún Sứa, nem nướng, Bún Cá Thu',
         'd':'Cơm Hến, bún hến, chè thập cẩm',
         'true':'b',
        },
        {
         'ques':'Giới trẻ Sài Gòn thường hẹn nhau ở “Cà Phê Bệt”. Đó là địa điểm nào?',
         'a':'Cạnh chợ Lớn',
         'b':'Cạnh Lăng Ông Bà Chiểu',
         'c':'Cạnh Nhà Thờ Đức Bà',
         'd':'Cạnh Hầm Thủ Thiêm',
         'true':'c',
        },
     ],
   },
   {
     'category':'Đề số 3',
     'question':
     [
        {
         'ques':'Có một bài hát được nhạc sĩ Hà Okio sáng tác, nói về thức uống đậm chất Sài Gòn. Đó là bài hát nào?',
         'a':'Sài Gòn cà phê sữa Đá',
         'b':'Sài Gòn sữa Đá cà phê',
         'c':'Cà phê sữa đá Sài Gòn',
         'd':'Phê Phê Sài Gòn sữa đá',
         'true':'a',
        },
        {
         'ques':'Một tòa nhà 68 tầng, được xem là biểu tượng mới, thể hiện chất Sài Gòn hội nhập phát triển.',
         'a':'Tòa nhà Keangnam',
         'b':'Tòa nhà Time Square',
         'c':'Tòa nhà Bitexco',
         'd':'Tòa nhà STC(Prudential)',
         'true':'c',
        },
        {
         'ques':'Một vòng xoay (công trường) có đài phun nước, nối 3 đường Phạm Ngọc Thạch, Trần Cao Vân, Võ Văn Tần là',
         'a':'Công xã Paris',
         'b':'Công trường Dân Chủ',
         'c':'Công trường Quốc Tế',
         'd':'Công trường Mê Linh',
         'true':'c',
        },
        {
         'ques':'Khu chợ nào được thành lập từ 2 ngôi chợ Kim Biên và Bình Tây ở quận 5?',
         'a':'Chợ Nhỏ',
         'b':'Chợ Lớn',
         'c':'Chợ Tàu',
         'd':'Chợ Ta',
         'true':'b',
        },
        {
         'ques':'Tuyến đường nhộn nhịp của Sài Gòn, được tái cải tạo từ trục đường có sẵn ở cổng Nam thành phố theo hướng Đông – Tây',
         'a':'Đường Điện Biên Phủ',
         'b':'Đại lộ Võ Văn Kiệt',
         'c':'Đường Tôn Đức Thắng',
         'd':'Đường Nguyễn Tất Thành',
         'true':'b',
        },
     ],
   },
]
