var title =
[
   {
      'category':'Chợ,trung tâm mua sắm',
      'question':
      [
       {
         'ques':'Một khu chợ đậm chất SG cổ kính, một biểu tượng của thành phố từ thời Pháp thuộc',
         'a':'Chợ Bà Chiểu',
         'b':'Chợ Bình Tây',
         'c':'Chợ Bến Thành',
         'd':'Chợ An Đông',
         'answer':'',
         'true':'c',
        },
        {
         'ques':'Khu chợ nào được thành lập từ 2 ngôi chợ Kim Biên và Bình Tây ở quận 5?',
         'a':'Chợ Nhỏ',
         'b':'Chợ Lớn',
         'c':'Chợ Tàu',
         'd':'Chợ Ta',
         'answer':'',
         'true':'b',
        },
        {
         'ques':'Một trung tâm thương mại do Phú Mỹ Hưng đầu tư với thiết kế vòng cung độc đáo, gần cầu Ánh Sao.',
         'a':'Diamond Plaza',
         'b':'Aeon Mall',
         'c':'Crescent Mall',
         'd':'Saigon Square',
         'answer':'',
         'true':'c',
        },
     ],
   },
   {
     'category':'Cầu',
     'question':
     [
        {
         'ques':'Một cây cầu đi bộ thu hút giới trẻ Sài Gòn ở quận 7 với hệ thống đèn LED và hệ thống phun nước lung linh.',
         'a':'Cầu Xanh',
         'b':'Cầu Thủ Thiêm',
         'c':'Cầu Phú Mỹ',
         'd':'Cầu Sài Gòn',
         'answer':'',
         'true':'d',
        },
        {
         'ques':'Là công trình vượt lòng sông Sài Gòn, nối liền quận 1 và khu đô thị mới Thủ Thiêm.',
         'a':'Cầu Thủ Thiêm',
         'b':'Hầm Thủ Thiêm',
         'c':'Cầu Phú Mỹ',
         'd':'Cầu Sài Gòn',
         'answer':'',
         'true':'b',
        },
        {
         'ques':'Một cây cầu nối liền quận 1 và quận 4, dẫn ngang qua địa danh lịch sử, nơi Bác Hồ ra đi tìm đường cứu nước.',
         'a':'Cầu Kiệu',
         'b':'Cầu Cống',
         'c':'Cầu Ông Lãnh',
         'd':'Cầu Khánh Hội',
         'answer':'',
         'true':'d',
        },
     ],
   },
   {
     'category':'Con đường',
     'question':
     [
        {
         'ques':'Tuyến đường nhộn nhịp của Sài Gòn, được tái cải tạo từ trục đường có sẵn ở cổng Nam thành phố theo hướng Đông – Tây',
         'a':'Đường Điện Biên Phủ',
         'b':'Đại lộ Võ Văn Kiệt',
         'c':'Đường Tôn Đức Thắng',
         'd':'Đường Nguyễn Tất Thành',
         'answer':'',
         'true':'b',
        },
        {
         'ques':'Biệt danh giới trẻ Sài Gòn đặt cho đường Đề Thám, Bùi Viện, Phạm Ngũ Lão, Đỗ Quang Đẩu là gì?',
         'a':'Phố đi bộ',
         'b':'Phố đồ cũ',
         'c':'Phố Tây',
         'd':'Phố ăn vặt',
         'answer':'',
         'true':'c',

        },
        {
         'ques':'Tên gọi thân thương người Sài Gòn dành cho những con đường Trần Huy Liệu, Trần Nhân Tôn, Nguyễn Thị Minh Khai.',
         'a':'Phố đi bộ',
         'b':'Phố Tây',
         'c':'Phố sách cũ',
         'd':'Phố ăn vặt',
         'answer':'',
         'true':'c',
        },
     ],
   },
   {
     'category':'Năm tuổi của một số địa danh nổi tiếng ở SG',
     'question':
     [
        {
         'ques':'Một địa điểm nằm ngay trên đường Đồng Khởi như nàng thơ kiêu sa của Sài Gòn với lối kiến trúc Opera Garnier.',
         'a':'Nhà hát thành phố',
         'b':'Tòa nhà Vincom',
         'c':'Công viên Chi Lăng',
         'd':'Khách sạn Sheraton',
         'answer':'',
         'true':'a',
        },
        {
         'ques':'Một địa điểm gắn liền với sự kiện giải phóng miền Nam, nằm trên đường Nam Kỳ Khởi Nghĩa.',
         'a':'Café bệt',
         'b':'Dinh Độc Lập',
         'c':'Trường THPT Marie Curie',
         'd':'Chùa Vĩnh Nghiêm',
         'answer':'',
         'true':'b',
        },
        {
         'ques':'Một nhà thờ Công Giáo lâu đời, gần Dinh Độc Lập, thu hút rất nhiều bạn trẻ tham quan và chụp ảnh.',
         'a':'Nhà thờ Đức Bà',
         'b':'Nhà thờ Tân Định',
         'c':'Nhà thờ Dòng Chúa Cứu Thế',
         'd':'Nhà thờ Huyện Sĩ',
         'answer':'',
         'true':'a',
        },
        {
         'ques':'Khu công viên đặc trưng của văn hóa vỉa hè, thu hút rất nhiều bạn trẻ. Nằm gần nhà thờ Đức Bà.',
         'a':'Công viên 30/4',
         'b':'Công viên 23/9',
         'c':'Công viên Lê Văn Tám',
         'd':'Công viên Tao Đàn',
         'answer':'',
         'true':'a',
        },
        {
         'ques':'Một địa điểm ‘chất lạ’ ở trung tâm quận 1, được bạn bè quốc tế gọi là Black Forest (rừng đen).',
         'a':'Công viên Lê Thị Riêng',
         'b':'Công viên Gia Định',
         'c':'Công viên Lê Văn Tám',
         'd':'Công viên 23/9',
         'answer':'',
         'true':'d',
        },
        {
         'ques':'Một tòa nhà 68 tầng, được xem là biểu tượng mới, thể hiện chất Sài Gòn hội nhập phát triển.',
         'a':'Tòa nhà Keangnam',
         'b':'Tòa nhà Time Square',
         'c':'Tòa nhà Bitexco',
         'd':'Tòa nhà STC(Prudential)',
         'answer':'',
         'true':'c',
        },
        {
         'ques':'Một công trình mới, thu hút người Sài Gòn đến hóng mát, đi dạo. Gần thương xá Tax, khách sạn Rex.',
         'a':'Hầm Thủ Thiêm',
         'b':'Phố đi bộ Nguyễn Huệ',
         'c':'Cầu ánh sao',
         'd':'Phố tây',
         'answer':'',
         'true':'b',
        },
        {
         'ques':'Tòa nhà cao nhất, còn gọi là biểu tượng Sài Gòn có bao nhiêu tầng?',
         'a':'69',
         'b':'96',
         'c':'68',
         'd':'52',
         'answer':'',
         'true':'c',
        },
        {
         'ques':'Khu kênh rạch được cải tạo suốt nhiều năm từ khu nhà lụp xụp dọc bờ kênh là…',
         'a':'Hồ con rùa',
         'b':'Sông Sài Gòn',
         'c':'Kênh Nhiêu Lộc',
         'd':'Khu du lịch Đầm Sen',
         'answer':'',
         'true':'c',
        },
        {
         'ques':'Mộtvòng xoay có đài phun nước, nối 3 đường Phạm Ngọc Thạch, Trần Cao Vân,  Võ Văn Tần là…',
         'a':'Nhà thờ Đức Bà',
         'b':'Vòng xoay Dân Chủ',
         'c':'Hồ con rùa',
         'd':'Công trường Mê Linh',
         'answer':'',
         'true':'c',
        },
     ],
   },
   {
     'category':'Món ăn đặc trưng của SG',
     'question':
     [
        {
         'ques':'Một loại chè đã làm mưa làm gió giới trẻ Việt Nam nói chung và Sài Gòn nói riêng trong 1 thời gian dài đó là chè',
         'a':'Khúc côn cầu',
         'b':'Khúc cây',
         'c':'Khúc mắc',
         'd':'Khúc bạch',
         'answer':'',
         'true':'d',
        },
        {
         'ques':'Ẩm thực đặc trưng chưa xa đã nhớ của Sài Gòn là món nào sau đây?',
         'a':'Bún đậu mắm tôm,bún chả,trà chanh',
         'b':'Cơm tấm,phở,cà phê sữa đá',
         'c':'Bún Sứa, Nem nướng, Bún Cá Thu',
         'd':'Cơm Hến, Bún hến, chè thập cẩm',
         'answer':'',
         'true':'b',
        },
        {
         'ques':'Món ăn vặt đậm chất Sài Gòn, được bình chọn là món ăn ưa thích nhất của giới trẻ năm 2014.',
         'a':'Cơm cháy',
         'b':'Gỏi cuốn',
         'c':'Gỏi khô bò',
         'd':'Bánh tráng trộn',
         'answer':'',
         'true':'d',
        },
     ],
   },
   {
     'category':'Một số câu hỏi liên quan tới trào lưu giới trẻ SG',
     'question':
     [
        {
         'ques':'Con phố đi bộ người dân Sài Gòn yêu thích nhất nằm trên trục đường nào?',
         'a':'Đồng Khởi',
         'b':'Nguyễn Huệ',
         'c':'Nam Kỳ Khởi Nghĩa',
         'd':'Phạm Ngũ Lão',
         'answer':'',
         'true':'b',
        },
        {
         'ques':'Giới trẻ Sài Gòn thường hẹn nhau ở “Cà Phê Bệt”. Đó là địa điểm nào?',
         'a':'Cạnh chợ Lớn',
         'b':'Cạnh Lăng Ông Bà Chiểu',
         'c':'Cạnh Nhà Thờ Đức Bà',
         'd':'Cạnh Hầm Thủ Thiêm',
         'answer':'',
         'true':'c',
        },
     ],
   },
   {
     'category':'Một số danh nhân nổi tiếng ở SG',
     'question':
     [
        {
         'ques':'Dấu ấn Sài Gòn xưa với hình ảnh vị sư thiêu sống mình tại ngã tư Cách Mạng Tháng 8 và Nguyễn Đình Chiểu. Đó là?',
         'a':'Võ Thị Sáu',
         'b':'Thích Quãng Đức',
         'c':'Phan Đình Phùng',
         'd':'Hàm Nghi',
         'answer':'',
         'true':'b',
        },
        {
         'ques':'Tên của một danh nhân được đặt tên trên con đường này và nó nối liền với con đường Nam Kỳ Khởi Nghĩa',
         'a':'Nguyễn Văn Trỗi',
         'b':'Nguyễn Văn Linh',
         'c':'Nguyễn Văn Cừ',
         'd':'Nguyễn Văn Đậu',
         'answer':'',
         'true':'a',
        },
        {
         'ques':'Một trường chuyên THPT nằm trên đường Lê Quý Đôn, được đặt tên theo một vị quan thời xưa:',
         'a':'Lê Văn Tám',
         'b':'Lê Quý Đôn',
         'c':'Nguyễn Thái Bình',
         'd':'Marie Curie',
         'answer':'',
         'true':'b',
        },
     ],
   },
   {
     'category':'Bài hát về SG',
     'question':
     [
        {
         'ques':'Có một bài hát được nhạc sĩ Hà Okio sáng tác, nói về thức uống đậm chất Sài Gòn. Đó là bài hát nào?',
         'a':'Sài Gòn cà phê sữa Đá',
         'b':'Sài Gòn sữa Đá cà phê',
         'c':'Cà phê sữa đá Sài Gòn',
         'd':'Phê Phê Sài Gòn sữa đá',
         'answer':'',
         'true':'a',
        },
        {
         'ques':'Câu hát“Sài Gòn đẹp quá Sài Gòn ơi…..” nằm trong bài hát nào về Sài Gòn thân thương?',
         'a':'Đẹp lắm Sài Gòn',
         'b':'Sài Gòn Đẹp Lắm',
         'c':'Sài Gòn trong tôi',
         'd':'Tôi trong Sài Gòn',
         'answer':'',
         'true':'b',
        },
        {
         'ques':'Nhóm nhạc MTV nổi tiếng với một ca khúc Rock viết về Sài Gòn. Đó là ca khúc nào?',
         'a':'Rock Sài Gòn',
         'b':'Tìm lại',
         'c':'Nối vòng tay lớn',
         'd':'Đám cưới chuột',
         'answer':'',
         'true':'a',
        },
     ],
   },
]